name: Go

on:
  push:
    branches: [ "verify-egress", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make

    - name: Test
      # test failure should not cause a failure of the whole workflow
      run: make test || true
